# -*- coding: utf-8 -*-
"""CAPSTONE 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ENZxqbvBK6of5ibBDuLWbBWkQIeDd9Z
"""

!pip install sqlalchemy==1.3.9

!pip install ipython-sql
!pip install ipython-sql prettytable

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql

import csv
import sqlite3
import prettytable
prettytable.DEFAULT = 'DEFAULT'

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

!pip install -q pandas

import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

# Commented out IPython magic to ensure Python compatibility.
#DROP THE TABLE IF EXISTS

# %sql DROP TABLE IF EXISTS SPACEXTABLE;

# Commented out IPython magic to ensure Python compatibility.
# %sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT * FROM SPACEXTABLE LIMIT 5

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT DISTINCT Launch_Site FROM SPACEXTABLE

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT * FROM SPACEXTABLE WHERE Launch_Site LIKE 'CCA%' LIMIT 5

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT SUM(PAYLOAD_MASS__KG_) AS TotalPayloadMass FROM SPACEXTABLE WHERE Customer = 'NASA (CRS)'

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT Date FROM SPACEXTABLE WHERE Landing_Outcome = 'Success (ground pad)' ORDER BY Date ASC LIMIT 1

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT Booster_Version FROM SPACEXTABLE WHERE Landing_Outcome = 'Success (drone ship)' AND PAYLOAD_MASS__KG_ > 4000 AND PAYLOAD_MASS__KG_ < 6000

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT Mission_Outcome, COUNT(*) AS Total FROM SPACEXTABLE GROUP BY Mission_Outcome

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT Booster_Version FROM SPACEXTABLE WHERE PAYLOAD_MASS__KG_ = (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEXTABLE)

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT STRFTIME('%M', Date) AS Month, Landing_Outcome, Booster_Version, Launch_Site FROM SPACEXTABLE WHERE STRFTIME('%Y', Date) = '2015' AND Landing_Outcome = 'Failure (drone ship)'

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT Landing_Outcome, COUNT(*) AS Count FROM SPACEXTABLE WHERE Date BETWEEN '2010-06-04' AND '2017-03-20' GROUP BY Landing_Outcome ORDER BY Count DESC

!pip install numpy pandas seaborn

import pandas as pd
#NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np
# Matplotlib is a plotting library for python and pyplot gives us a MatLab like plotting framework. We will use this in our plotter function to plot data.
import matplotlib.pyplot as plt
#Seaborn is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics
import seaborn as sns

import pandas as pd

URL = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_2.csv"
df=pd.read_csv(URL)
df.head(5)

sns.catplot(y="PayloadMass", x="FlightNumber", hue="Class", data=df, aspect = 5)
plt.xlabel("Flight Number",fontsize=20)
plt.ylabel("Pay load Mass (kg)",fontsize=20)
plt.show()

sns.catplot (y="LaunchSite", x="PayloadMass", hue="Class", data= df, aspect= 5)
plt.xlabel ("Pay Load Mass", fontsize=20 )
plt.ylabel ("Launch Site", fontsize= 20)
plt.show ()

sns.catplot (x="PayloadMass", y="LaunchSite", hue="Class", data= df, aspect= 5)
plt.xlabel ("Pay Load Mass (kg)", fontsize=20 )
plt.ylabel ("Launch Site", fontsize= 20)
plt.show ()



# Group by Orbit and calculate the mean of Class column
orbit_success_rate = df.groupby('Orbit')['Class'].mean()

# Create a bar chart of the success rate for each orbit
plt.figure(figsize=(8, 5))
sns.barplot(x=orbit_success_rate.index, y=orbit_success_rate.values)
plt.xlabel("Orbit", fontsize=8)
plt.ylabel("Success Rate", fontsize=8)
plt.title("Success Rate by Orbit Type", fontsize=8)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()



import seaborn as sns
import matplotlib.pyplot as plt

sns.catplot(x="FlightNumber", y="Orbit", hue="Class", data=df, aspect = 5)
plt.xlabel("Flight Number",fontsize=20)
plt.ylabel("Orbit",fontsize=20)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.catplot(x="PayloadMass", y="Orbit", hue="Class", data=df, aspect = 5)
plt.xlabel("Payload Mass (kg)",fontsize=20)
plt.ylabel("Orbit",fontsize=20)
plt.show()

year=[]
def Extract_year():
    for i in df["Date"]:
        year.append(i.split("-")[0])
    return year
Extract_year()
df['Date'] = year
df.head()

"""###### Plot a line chart with x axis to be the extracted year and y axis to be the success rate"""

# Group by year and calculate the average success rate
yearly_success_rate = df.groupby('Date')['Class'].mean()

# Plot a line chart of the yearly success rate
plt.figure(figsize=(10, 6))
sns.lineplot(x=yearly_success_rate.index, y=yearly_success_rate.values)
plt.xlabel("Year", fontsize=20)
plt.ylabel("Average Success Rate", fontsize=20)
plt.title("Yearly Launch Success Trend", fontsize=20)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

features = df[['FlightNumber', 'PayloadMass', 'Orbit', 'LaunchSite', 'Flights', 'GridFins', 'Reused', 'Legs', 'LandingPad', 'Block', 'ReusedCount', 'Serial']]
features.head()

features_one_hot = pd.get_dummies(features, columns=['Orbit', 'LaunchSite', 'LandingPad', 'Serial'])
display(features_one_hot.head())

features_one_hot = features_one_hot.astype('float64')
display(features_one_hot.head())

features_one_hot.to_csv('dataset_part_3.csv', index=False)

# Get the number of columns
num_columns = features_one_hot.shape[1]

# Display the number of columns
print(f"The total number of columns in the features_one_hot DataFrame is: {num_columns}")

cols= features.shape[1]
print(cols)

