# -*- coding: utf-8 -*-
"""Capstone 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-hzrxU2tPoJVbHDPloiI0uPrN5U4HRnU
"""

# Install required packages
!pip install folium pandas

import folium
import pandas as pd

# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
spacex_df = pd.read_csv(URL)

spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

# Create a blue circle marker for each launch site
for index, site in launch_sites_df.iterrows():
    circle = folium.Circle(
        location=[site['Lat'], site['Long']],
        radius=1000,
        color='#0000FF',
        fill=True,
        fill_color='#0000FF',
        fill_opacity=0.1,
        popup=site['Launch Site']
    ).add_to(site_map)

    # Add a red icon to the circle to display the launch site name
    marker = folium.Marker(
        location=[site['Lat'], site['Long']],
        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % site['Launch Site'],
            )
    ).add_to(site_map)

site_map

circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

marker_cluster = MarkerCluster()

"""Create a MarkerCluster object

Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` column.
"""

spacex_df['marker_color'] = spacex_df['class'].apply(lambda x: 'red' if x == 0 else 'green')
spacex_df.head()

"""For each launch result in the `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`"""

# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate and customize the icon color attribute
for index, record in spacex_df.iterrows():
    # Create and add a Marker to the MarkerCluster
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        icon=folium.Icon(color='white', icon_color=record['marker_color']),
        popup=f"Launch Site: {record['Launch Site']}, Outcome: {'Success' if record['class'] == 1 else 'Failure'}"
    )
    marker_cluster.add_child(marker)

site_map

"""For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a pop-up label"""

# Create a blue circle marker for each launch site
for index, site in launch_sites_df.iterrows():
    circle = folium.Circle(
        location=[site['Lat'], site['Long']],
        radius=1000,
        color='#0000FF',
        fill=True,
        fill_color='#0000FF',
        fill_opacity=0.1,
        popup=site['Launch Site']
    ).add_to(site_map)

    # Add a red icon to the circle to display the launch site name
    marker = folium.Marker(
        location=[site['Lat'], site['Long']],
        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % site['Launch Site'],
            )
    ).add_to(site_map)

site_map

spacex_df.tail(10)

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red
spacex_df['marker_color'] = spacex_df['class'].apply(lambda x: 'green' if x == 1 else 'red')

# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed,
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # Create and add a Marker cluster to the site map
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        icon=folium.Icon(color='white', icon_color=record['marker_color']),
        popup=f"Launch Site: {record['Launch Site']}, Outcome: {'Success' if record['class'] == 1 else 'Failure'}"
    )
    marker_cluster.add_child(marker)

site_map

formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

"""Find the coordinates of the closest coastline and calculate the distance to the launch site."""

# Select a launch site (e.g., the first one in launch_sites_df)
launch_site_lat = launch_sites_df.loc[0, 'Lat']
launch_site_lon = launch_sites_df.loc[0, 'Long']

# Approximate coordinates of a nearby coastline point (You might need to adjust these)
coastline_lat = 28.56367
coastline_lon = -80.56764

# Calculate the distance to the coastline
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

print(f"Distance from the launch site at ({launch_site_lat}, {launch_site_lon}) to the coastline at ({coastline_lat}, {coastline_lon}): {distance_coastline:.2f} km")

# Create a marker for the coastline point
distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_coastline),
    )
)

# Add the marker to the map
site_map.add_child(distance_marker)

site_map

"""Find the coordinates of a nearby city (Titusville) and calculate the distance to the launch site."""

# Select a launch site (e.g., the first one in launch_sites_df)
launch_site_lat = launch_sites_df.loc[0, 'Lat']
launch_site_lon = launch_sites_df.loc[0, 'Long']

# Approximate coordinates of a nearby city (Titusville, Florida)
city_lat = 28.6123
city_lon = -80.8077

# Calculate the distance to the city
distance_city = calculate_distance(launch_site_lat, launch_site_lon, city_lat, city_lon)

print(f"Distance from the launch site at ({launch_site_lat}, {launch_site_lon}) to Titusville at ({city_lat}, {city_lon}): {distance_city:.2f} km")

"""Create a marker with distance to the city and add it to the map."""

# Create a marker for the city point
distance_marker_city = folium.Marker(
    [city_lat, city_lon],
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_city),
    )
)

# Add the marker to the map
site_map.add_child(distance_marker_city)

site_map

"""Draw a line between the launch site and the city marker."""

# Create a list of the launch site and city coordinates
coordinates_city = [[launch_site_lat, launch_site_lon], [city_lat, city_lon]]

# Create a `folium.PolyLine` object using the coordinates
lines_city = folium.PolyLine(locations=coordinates_city, weight=1)

# Add the PolyLine to the map
site_map.add_child(lines_city)

site_map

# Create a list of the launch site and coastline coordinates
coordinates = [[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]]

# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
lines = folium.PolyLine(locations=coordinates, weight=1)

# Add the PolyLine to the map
site_map.add_child(lines)

site_map